import './globals.css'
import type { Metadata } from 'next'

// Components
import { Navbar } from '@/components'

// Fonts
import localFont from 'next/font/local'
const satoshi = localFont({ src: '../../public/fonts/Satoshi-Variable.ttf' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <nav className="mx-32 my-10">
        <Navbar />
      </nav>
      <body className={`${satoshi.className} text-dark bg-light`}>
        {children}
      </body>
    </html>
  )
}
